CREATE TABLE IF NOT EXISTS client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,

    CONSTRAINT ck_client_name CHECK (LENGTH(name) BETWEEN 2 AND 200)
);

CREATE TABLE IF NOT EXISTS planet (
    id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(500) NOT NULL,

    CONSTRAINT ck_planet_id CHECK (id REGEXP '^[A-Z0-9]+$'),
    CONSTRAINT ck_planet_name CHECK (LENGTH(name) BETWEEN 1 AND 500)
);

CREATE TABLE IF NOT EXISTS ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE
     NOT NULL
     DEFAULT CURRENT_TIMESTAMP(0),
    client_id BIGINT NOT NULL,
    from_planet_id VARCHAR(10) NOT NULL,
    to_planet_id VARCHAR(10) NOT NULL,

    CONSTRAINT fk_ticket_client_id FOREIGN KEY (client_id)
    REFERENCES client(id),
    CONSTRAINT fk_ticket_from_planet_id FOREIGN KEY (from_planet_id)
    REFERENCES planet(id),
    CONSTRAINT fk_ticket_to_planet_id FOREIGN KEY (to_planet_id)
    REFERENCES planet(id),
    CONSTRAINT ck_ticket_planet CHECK (from_planet_id <> to_planet_id)
);